language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: osx
      osx_image: xcode9.1
      install:
        - brew update > /dev/null
        - brew install curl --with-openssl
        - brew tap caskroom/cask
        - brew cask install powershell

install: true
  # - sudo chmod +x ./build/travis/install-dependencies.sh
  # - ./build/travis/install-dependencies.sh
  # - sudo pwsh -file ./build/shared/install-dependencies.ps1

script:
  - pwsh -v
  # - pwsh -file ./build/shared/build.ps1
  # - pwsh -file ./tests/start-tests.ps1
