language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: "deb https://packages.microsoft.com/config/ubuntu/14.04/prod.list main"
                key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    #- os: osx
      #osx_image: xcode9.1

install: true
  # - sudo chmod +x ./build/travis/install-dependencies.sh
  # - ./build/travis/install-dependencies.sh
  # - sudo pwsh -file ./build/shared/install-dependencies.ps1

script: true
  # - pwsh -file ./build/shared/build.ps1
  # - pwsh -file ./tests/start-tests.ps1
