#          YAML Reference Guide: https://www.appveyor.com/docs/appveyor-yml/
# Environmental Variables Guide: https://www.appveyor.com/docs/environment-variables/
#                YAML Validator: https://ci.appveyor.com/tools/validate-yaml

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.


#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0.{build}

# branches to build
#branches:
  # whitelist
  #only:
    #- master

  # blacklist
  #except:

# Do not build on tags
#skip_tags:

# Start builds on tags only
#skip_non_tags:

# Skipping commits with particular message, from specific users, or for specific files
#skip_commits:
  #message: /Merge branch .+ of .+ArmorPowerShell/
  #author:
  #files:
    #- README.md

# Including commits with particular message, from specific users, or for specific files
#only_commits:
  #message:
  #author:
  #files:

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# Do not build feature branch with open Pull Requests
#skip_branch_with_pr:

# Maximum number of concurrent jobs for the project
#max_jobs:


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2015
  #- Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
#init:
  #- git config --global core.autocrlf input

# clone directory
#clone_folder:

# fetch repository as zip archive
# default is "false"
#shallow_clone:

# set clone depth
# clone entire repository history if not defined
#clone_depth:

# setting up etc/hosts file
#hosts:

# environment variables
#environment:

# this is how to allow failing jobs in the matrix
#matrix:
  # set this flag to immediately finish build once one of the jobs fails.
  #fast_finish:
  #allow_failures:
    #- platform: x86
      #configuration: Debug
    #- platform: x64
      #configuration: Release

# exclude configuration from the matrix. Works similarly to 'allow_failures' but build not even being started for excluded combination.
  #exclude:
    #- platform: x86
      #configuration: Debug

# build cache to preserve files/folders between builds
#cache:

# enable service required for build/tests
#services:
  #- mssql2014           # start SQL Server 2014 Express
  #- mssql2014rs         # start SQL Server 2014 Express and Reporting Services
  #- mssql2012sp1        # start SQL Server 2012 SP1 Express
  #- mssql2012sp1rs      # start SQL Server 2012 SP1 Express and Reporting Services
  #- mssql2008r2sp2      # start SQL Server 2008 R2 SP2 Express
  #- mssql2008r2sp2rs    # start SQL Server 2008 R2 SP2 Express and Reporting Services
  #- mysql               # start MySQL 5.6 service
  #- postgresql          # start PostgreSQL 9.5 service
  #- iis                 # start IIS
  #- msmq                # start Queuing services
  #- mongodb             # start MongoDB

# scripts that run after cloning repository
# by default, all script lines are interpreted as batch
install:
  - ps: Install-Module -Name 'Pester' -Scope 'CurrentUser' -Force -Confirm:$false -Verbose
  - ps: Write-Host -Object ( 'AppVeyor PR#- "{0}""' -f $env:APPVEYOR_PULL_REQUEST_NUMBER )

# enable patching of AssemblyInfo.* files
#assembly_info:
  #patch:
  #file:
  #assembly_version:
  #assembly_file_version:
  #assembly_informational_version:


# Automatically register private account and/or project AppVeyor NuGet feeds.
#nuget:
  #account_feed:
  #project_feed:
  #disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds


#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
#before_build:

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform:
  #- Any CPU

# build Configuration, i.e. Debug, Release, etc.
#configuration:

# to disable automatic builds
build: off

# to run your custom scripts instead of automatic MSBuild
#build_script:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
#before_package:

# scripts to run after build
#after_build:


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
#before_test:

# to run tests again only selected assemblies and/or categories
#test:
  #assemblies:
    #only:

  #categories:
    #only:

# to disable automatic tests
#test: off

# to run your custom scripts instead of automatic tests
#test_script:

# scripts to run after tests
#after_test:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

# Files generated during the build process that should be retained
#artifacts:
#  path: 


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# scripts to run before deployment
#before_deploy:

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
#deploy: off

# to run your custom scripts instead of provider deployments
#deploy_script:

# scripts to run after deployment
#after_deploy:


#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  - ps: Write-Host -Object 'Hello world!'
  on:
    branch: master

# on build failure
#on_failure:

# after build failure or success
#on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
